name: E2E Tests

on: [pull_request]

jobs:
  e2e-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
        registry-url: 'https://registry.npmjs.org'

    - name: Cache node_modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: dependency-cache-{{ hashFiles('package.json') }}
        restore-keys: |
          dependency-cache-
    
    - name: Install dependencies and verify Cypress
      run: npm ci
           npm run cypress:verify
           npm run clean-reports
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Run UI Tests
      run: npm run test:ui

    - name: Copy test execution screenshots
      run: |
          mkdir report
          cp -r cypress/screenshots report/screenshots
      if: failure()
    
    - name: Merge test reports
      run: npm run merge-report
      if: always()

    - name: Generate HTML report
      run: npm run generate-report
      if: always()

    - name: Upload report
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: report
        path: ./report

    - name: Run API Tests
      run: npm run test:ui

    - name: Copy test execution screenshots
      run: |
          mkdir report
          cp -r cypress/screenshots report/screenshots
      if: failure()
    
    - name: Merge test reports
      run: npm run merge-report
      if: always()

    - name: Generate HTML report
      run: npm run generate-report
      if: always()

    - name: Upload report
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: report
        path: ./report